apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helmChartTwo.service.name }}-nginx-service
  namespace: argocd-test
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helmChartTwo.service.type }}
  ports:
    - port: {{ .Values.helmChartTwo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
